### ISSUE TITLE
Port 7676 is closed

### ISSUE THREAD

**Issue by mjm29se** [noia-network/noia-node-gui#8]
Status on port forward check of default port 7676 is closed. Issue or not?
I do not see anything else in the dashboard that indicates I am connected other than it shows connected and the time connected ticks over.

**Comment by Dancia** [comment]
Closed 7676 port has some implications, but not how you expect it. 

First thing you are seeing when you click "Connect" button, is that your client connects to master.  Please note that node IS connecting TO master, its OUTGOING connection. In this scenario you don't have to worry about ports. It has nothing to do with mentioned port 7676. 

You might be wondering now why do you need port 7676 to be opened. This port is required if node wants to accept INCOMING connections: connections from browsers and other devices TO node client. Since we still aren't pushing any content, you see no implications of port 7676 being closed, but once we will start pushing content to nodes, nodes which will have 7676 closed will not be able to deliver content, because communication will be closed. It means that you will not be able to generate UPLOADED data.

**Comment by ouallada** [comment]
HI,
port 7676 was closed , hi  open it in my box, check open
but still have no connection download or upload

**Comment by mjm29se** [comment]
Hi Dancia, 
For the testnet, the conclusion is the port needs to be opened or closed? Do I need to forward the port?

**Comment by Zippo85** [comment]
Hi Dancia, Can you provide a guide to set this up for OS X? Port forwarding is not working for me either.

**Comment by Dancia** [comment]
@ouallada @mjm29se @Zippo85 where is no such guide yet. I have created #22 to address this issue in the future. Stay tuned!
